language: php
php:
    - 5.6

services:
    - redis

sudo: required
dist: trusty
group: edge

env:
    - DB=mysql

addons:
    hosts:
        - misp.local
        - localhost
    apt:
        packages:
            - mysql-server
            - python-dev
            - python-pip
            - libxml2-dev
            - zlib1g-dev
            - php5-dev
            - apache2
            - libapache2-mod-php5
            - curl
            - python-virtualenv
            - python-pip
            - php5-mysql

install:
    - git pull --recurse-submodules && git submodule update
    - pip install --user pyzmq
    - pip install --user coveralls
    - pip install --user codecov
    - pip install --user git+https://github.com/CybOXProject/python-cybox.git@v2.1.0.12#egg=Package
    - pip install --user git+https://github.com/stixproject/python-stix.git@v1.2.0.0#egg=Package
    - pip install --user git+https://github.com/MISP/PyMISP.git#egg=Package
    - pear install Crypt_GPG
    - pear install Net_GeoIP
    - phpenv rehash
    - pushd app
    - composer require kamisama/cake-resque:4.1.2
    - composer config vendor-dir Vendor
    - composer install
    - popd
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty multiverse" && sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-updates multiverse"
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty universe" && sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-updates universe"
    - sudo apt-get update -qq
    - sudo apt-get install libapache2-mod-fastcgi php5-redis

before_script:
    # enable php-fpm
    #- sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    #- sudo a2enmod rewrite actions fastcgi alias
    #- echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    #- ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    # configure apache virtual hosts
    - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/misp.local.conf
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/misp.local.conf
    - sudo a2dissite 000-default
    - sudo a2ensite misp.local.conf
    - sudo service apache2 restart
    - phpenv config-add travis/myphpconfig.ini
    - mkdir .gnupg
    - sudo cp -a /dev/urandom /dev/random
    - gpg --homedir .gnupg --gen-key --batch travis/gpg
    - cp -fa INSTALL/setup/config.php app/Plugin/CakeResque/Config/config.php
    - cp travis/bootstrap.php app/Config/bootstrap.php
    - cp travis/database.php app/Config/database.php
    - cp travis/core.php app/Config/core.php
    - cp travis/config.php app/Config/config.php
    - mysql -u root -e 'create database misp;'
    - mysql -u root -e "grant usage on *.* to misp@localhost identified by 'blah'";
    - mysql -u root -e "grant all privileges on misp.* to misp@localhost;"
    - mysql -u misp -pblah misp < INSTALL/MYSQL.sql
    - AUTH=`app/Console/cake userInit -q`
    - sudo chown -R www-data:www-data app/
    - curl http://misp.local
    - pushd PyMISP
    - echo 'url = "http://misp.local"' >> tests/keys.py
    - echo 'key = "'${AUTH}'"' >> tests/keys.py
    - cat tests/keys.py
    - popd
    - sudo chown -R www-data:www-data ./
    - sudo chmod -R 755 /home/
    - sudo chmod 700 .gnupg
    - sudo chmod -R 777 app/tmp
    - sudo chmod -R 777 app/files
    - sudo chmod -R 777 app/files/scripts/tmp
    - sudo chmod -R 777 PyMISP

script:
    - pushd PyMISP
    - coverage run setup.py test
    - popd

after_failure:
    - curl http://misp.local
    - cat /etc/apache2/sites-available/misp.local.conf
    - sudo ls -l /var/log/apache2
    - sudo cat /var/log/apache2/error.log
    - sudo cat /var/log/apache2/misp.local_error.log
    - sudo cat /var/log/apache2/misp.local_access.log
    - pwd
    - sudo ls -lR ../../


after_success:
    - coveralls
    - codecov
