# Requirements: mkdocs >1.x && mkdocs-material && markdown_include

# Project information
site_name: MISP Install Documentation
site_description: MISP Project - Install Guides
site_author: MISP Project
site_url: https://www.misp-project.org/

# Repository
repo_name: MISP/MISP
repo_url: https://github.com/MISP/MISP
edit_uri: ""

#dev_addr: "192.168.10.34:8000"

# Copyright
copyright: "Copyright &copy; 2019 MISP Project"

# Options
extra:
  search:
    languages: "en"
  social:
    - type: globe
      link: https://www.misp-project.org/
    - type: github-alt
      link: https://github.com/MISP
    - type: twitter
      link: https://twitter.com/MISPProject

theme:
  name: material
  language: en
  favicon: img/favicon.ico
  logo: img/misp.png

# Extensions
markdown_extensions:
  - markdown_include.include:
      base_path: docs
  # mkdcomments is buggy atm, see: https://github.com/ryneeverett/python-markdown-comments/issues/3
  #- mkdcomments
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
    - Home: 'index.md'
    - Install Guides:
      - 'Ubuntu 18.04': 'INSTALL.ubuntu1804.md'
      - 'Kali Linux': 'INSTALL.kali.md'
      - 'RHEL7/CentOS7': 'INSTALL.rhel7.md'
      - 'RHEL8/CentOS8': 'INSTALL.rhel8.md'
    - xInstall Guides: 
      - 'Warning': 'xINSTALL.md'
      - 'Centos 6': 'xINSTALL.centos6.md'
      - 'Debian 10': 'xINSTALL.debian10.md'
      - 'Debian 9.9': 'xINSTALL.debian9.md'
      - 'Ubuntu 18.04 \w webmin': 'xINSTALL.ubuntu1804.with.webmin.md'
      - 'Tsurugi Linux': 'xINSTALL.tsurugi.md'
      - 'OpenBSD 6.5': 'xINSTALL.OpenBSD.md'
    - Config Guides:
      - 'Elastic Search Logging': 'CONFIG.elasticsearch-logging.md'
      - 'Amazon S3 attachments': 'CONFIG.s3-attachments.md'
      - 'S/MIME': 'CONFIG.SMIME.md'
    - Update MISP: 'UPDATE.md'
    - Upgrading MISP: 'UPGRADE.md'
    - Old guides:
      - '2.3 to 2.4 upgrade': 'archive/old-2_3to2_4-UPGRADE.md'
      - 'Ubuntu 16.04': 'archive/INSTALL.ubuntu1604.md'
      - 'FreeBSD': 'archive/xINSTALL.FreeBSD.md'
    - About:
      - 'MISP Release Notes': 'Changelog.md'
      - 'License': 'license.md'
